/**
 * Copyright 2013 Medium Entertainment, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.playhaven.android.diagnostic;

import android.app.Activity;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.SharedPreferences;
import android.content.res.Resources;
import android.os.Bundle;
import android.os.Handler;
import android.preference.PreferenceManager;
import android.util.Log;
import android.view.KeyEvent;
import android.view.Menu;
import android.view.MenuItem;
import android.view.inputmethod.EditorInfo;
import android.widget.*;

import com.google.android.gcm.GCMBroadcastReceiver;
import com.playhaven.android.Placement;
import com.playhaven.android.PlacementListener;
import com.playhaven.android.PlayHaven;
import com.playhaven.android.PlayHavenException;
import com.playhaven.android.data.DataCollectionField;
import com.playhaven.android.data.DataboundMapper;
import com.playhaven.android.data.Purchase;
import com.playhaven.android.data.Reward;
import com.playhaven.android.push.GCMRegistrationRequest;
import com.playhaven.android.req.MetadataRequest;
import com.playhaven.android.req.OpenRequest;
import com.playhaven.android.req.RequestListener;
import com.playhaven.android.req.model.ClientApiResponseModel;
import com.playhaven.android.view.*;

import java.util.ArrayList;

public class Launcher extends Activity implements PlacementListener, AdapterView.OnItemSelectedListener, RequestListener, DialogInterface.OnDismissListener, PlayHavenListener {
	private GCMReceiver pushReceiver;
	
    public enum RequestType
    {
        Open(R.string.req_open),
        Preload(R.string.req_preload),
        Content(R.string.req_content),
        Metadata(R.string.req_meta),
        Gcm(R.string.req_push_reg);

        RequestType(int id)
        {
            this.id = id;
        }
        private int id;
        public String toString(Resources resources){return resources.getString(id);}
    }

    private RequestType getRequestTypeForTitle(String title)
    {
        // RequestType.valueOf doesn't work since we are comparing to an autogenerated field
        Resources res = getResources();
        for(RequestType type : RequestType.values())
        {
            if(type.toString(res).equals(title))
                return type;
        }
        return null;
    }

    public enum ViewType
    {
        Activity(R.string.view_activity),
        Dialog(R.string.view_dialog);

        ViewType(int id)
        {
            this.id = id;
        }
        private int id;
        public String toString(Resources resources){return resources.getString(id);}
    }

    private ViewType getViewTypeForTitle(String title)
    {
        // ViewType.valueOf doesn't work since we are comparing to an autogenerated field
        Resources res = getResources();
        for(ViewType type : ViewType.values())
        {
            if(type.toString(res).equals(title))
                return type;
        }
        return null;
    }

    public static final String TAG = "PHDiagnosticApp";
    private static final int PH_REQUEST_CODE = 12345;
    private static final int MNU_SETTINGS = 0;
    private Placement placement;
    private Handler handler;
    private Spinner reqSpinner;
    private Spinner viewSpinner;

    private TextView.OnEditorActionListener editTextListener = new TextView.OnEditorActionListener()
    {
        @Override
        public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
            /**
             * Using the text watcher would cause us to set placement on the more games too often
             * So we will instead just watch for it to be done
             */
            if (actionId != EditorInfo.IME_ACTION_DONE) return false;

            EditText text = (EditText)v;
            String placementTag = text.getText().toString();
            if(placementTag == null || placementTag.length() == 0)
                return false;

            updatePlayHaven();
            placementTag = getPlacementTag();
            if(placementTag == null)
                return false;

            MoreGames more = (MoreGames) findViewById(R.id.more);
            more.setPlacementTag(placementTag);
            more.load(Launcher.this);
            return true;
        }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        handler = new Handler();
        setContentView(R.layout.main);

        EditText placementEditor = (EditText) findViewById(R.id.placementTag);
        placementEditor.setOnEditorActionListener(editTextListener);

        // Setup Request Type Spinner

        reqSpinner = (Spinner) findViewById(R.id.request_spinner);
        Resources res = getResources();
        ArrayList<String> reqTypes = new ArrayList<String>();
        for(RequestType type : RequestType.values())
            reqTypes.add(type.toString(res));

        ArrayAdapter<String> reqAdapter = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item, reqTypes);
        reqAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        reqSpinner.setAdapter(reqAdapter);
        reqSpinner.setOnItemSelectedListener(this);

        // Setup PlayHavenView Type Spinner

        viewSpinner = (Spinner) findViewById(R.id.viewtype_spinner);
        ArrayList<String> viewTypes = new ArrayList<String>();
        for(ViewType type : ViewType.values())
            viewTypes.add(type.toString(res));

        ArrayAdapter<String> viewAdapter = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item, viewTypes);
        viewAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        viewSpinner.setAdapter(viewAdapter);
        viewSpinner.setOnItemSelectedListener(this);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        menu.add(Menu.NONE, MNU_SETTINGS, 0, "Edit Settings");
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch(item.getItemId())
        {
            case MNU_SETTINGS:
                startActivity(new Intent(this, DiagnosticPreferences.class));
                return true;
        }
        return false;
    }

    private void updatePlayHaven()
    {
        try{
            SharedPreferences pref = PreferenceManager.getDefaultSharedPreferences(this);
            String token = DiagnosticPreferences.Pref.pref_token.getString(pref, "token");
            String secret = DiagnosticPreferences.Pref.pref_secret.getString(pref, "secret");
            String projectId = DiagnosticPreferences.Pref.pref_projectid.getString(pref, "push project id");
            String server = DiagnosticPreferences.Pref.pref_server.getString(pref);
            String fileName = DiagnosticPreferences.Pref.pref_file.getString(pref);

            /**
             * It doesn't allow us to use the integer values
             * http://code.google.com/p/android/issues/detail?id=2096
             * So we could just do Integer.parseInt
             * but then the preferences show "3" instead of "DEBUG"
             * so, we'll do it the hard way
             */
            PlayHaven.setLogLevel(DiagnosticPreferences.Pref.pref_log.getString(pref, "INFO"));

            if(fileName != null && fileName.length() > 0)
            {
                PlayHaven.configure(this, fileName);
            } 
			else {
	            PlayHaven.configure(this, token, secret, projectId);
                if(server != null && server.length() > 0)
                {
                    pref = PlayHaven.getPreferences(this);
                    SharedPreferences.Editor editor = pref.edit();
                    editor.putString(PlayHaven.Config.APIServer.toString(), server);
                    editor.commit();
                }
            }
        }catch(Exception e){
            Log.e(TAG, "Error", e);
        }
    }

    @Override
    protected void onPause() {
    	if(pushReceiver != null) unregisterReceiver(pushReceiver);
        Log.d(TAG, "onPause");
        super.onPause();
    }

    @Override
    protected void onResume() {
        Log.d(TAG, "onResume");
        super.onResume();
		
		// Have a local receiver to update the UI if we get registration results back. 
        if(pushReceiver != null) {
    		pushReceiver = new GCMReceiver();
    	    IntentFilter pushFilter = new IntentFilter();
    	    pushFilter.addAction(com.playhaven.android.push.GCMBroadcastReceiver.C2DM_RECEIVE);
    	    pushFilter.addAction(com.playhaven.android.push.GCMBroadcastReceiver.C2DM_REGISTRATION);
    	    pushFilter.addCategory(getPackageName());
    	    registerReceiver(pushReceiver, pushFilter);
        }
    }

    @Override
    public void onDismiss(DialogInterface dialog) {
        Windowed diag = (Windowed)dialog;
        Log.d(TAG, "Dialog was dismissed: " + diag.getPlacementTag());
    }

    public void doRequest(android.view.View target)
    {
        Spinner reqSpinner = (Spinner) findViewById(R.id.request_spinner);
        Spinner viewSpinner = (Spinner) findViewById(R.id.viewtype_spinner);

        try{
            RequestType requestType = getRequestTypeForTitle("" + reqSpinner.getSelectedItem());
            ViewType viewType = getViewTypeForTitle("" + viewSpinner.getSelectedItem());

            updatePlayHaven();

            if(requestType == RequestType.Open)
            {
                OpenRequest open = new OpenRequest();
                open.setResponseHandler(this);
                open.send(this);
                return;
            }
            else if (requestType == RequestType.Gcm)
            {
        		GCMRegistrationRequest regRequest = new GCMRegistrationRequest();
        		regRequest.send(this);
        		updateOutput("Registration request sent.");
        		return;
            }

            String placementTag = getPlacementTag();
            if(placementTag == null)
                return;

            switch(requestType)
            {
                case Preload:
                    placement = new Placement(placementTag);
                    placement.setListener(this);
                    placement.preload(this);
                    break;
                case Content:
                    int displayOpts = PlayHavenView.NO_DISPLAY_OPTIONS;

                    if( ((CheckBox)findViewById(R.id.auto)).isChecked() )
                    {
                        displayOpts |= PlayHavenView.AUTO_DISPLAY_OPTIONS;
                    }else{
                        if( ((CheckBox)findViewById(R.id.overlay)).isChecked() )
                            displayOpts |= PlayHavenView.DISPLAY_OVERLAY;

                        if( ((CheckBox)findViewById(R.id.animation)).isChecked() )
                            displayOpts |= PlayHavenView.DISPLAY_ANIMATION;
                    }

                    switch(viewType)
                    {
                        case Activity:
                            if(!FullScreen.timeElapsed(this, 10000))
                                Toast.makeText(this, "Quick quick quick!", Toast.LENGTH_SHORT).show();

                            if(placement != null && placement.getPlacementTag().equals(placementTag))
                                startActivityForResult(FullScreen.createIntent(this, placement, displayOpts), PH_REQUEST_CODE);
                            else
                                startActivityForResult(FullScreen.createIntent(this, placementTag, displayOpts), PH_REQUEST_CODE);
                            break;
                        case Dialog:
                            Windowed dialog = new Windowed(this);
                            dialog.setDisplayOptions(displayOpts);
                            if(placement == null)
                                dialog.setPlacementTag(placementTag);
                            else
                                dialog.setPlacement(placement);

                            dialog.setOnDismissListener(this);
                            dialog.setPlayHavenListener(this);
                            dialog.show();
                            break;
                        default:
                            break;
                    }
                    break;
                case Metadata:
                    MetadataRequest req = new MetadataRequest(placementTag);
                    req.setResponseHandler(this);
                    req.send(this);
                    break;
                default:
                    break;
            }
        }catch(Exception e){/* no-openContextMenu() */}
    }

    private String getPlacementTag()
    {
        String placementId = ((EditText)findViewById(R.id.placementTag)).getText().toString();
        if(placementId != null && placementId.length() > 0)
            return placementId;

        Toast.makeText(this,"Placement tag must be set", Toast.LENGTH_LONG).show();
        return null;
    }

    public void doMoreGames(android.view.View target)
    {
        updatePlayHaven();
        String placementTag = getPlacementTag();
        if(placementTag == null)
            return;

        int displayOpts = 0;

        if( ((CheckBox)findViewById(R.id.overlay)).isChecked() )
            displayOpts |= PlayHavenView.DISPLAY_OVERLAY;

        if( ((CheckBox)findViewById(R.id.animation)).isChecked() )
            displayOpts |= PlayHavenView.DISPLAY_ANIMATION;

        startActivityForResult(FullScreen.createIntent(this, "more_games", displayOpts), PH_REQUEST_CODE);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data)
    {
    	if(data == null)
    	{
    		PlayHaven.e("onActivityResult received a null intent");
    		placement = null;
    		return;
    	} 
    	
    	if(requestCode == PH_REQUEST_CODE)
        {
            Log.d(TAG, "Ad placement was: " + data.getStringExtra(PlayHavenView.BUNDLE_PLACEMENT_TAG));
            Log.d(TAG, "Ad display options were: " + data.getIntExtra(PlayHavenView.BUNDLE_DISPLAY_OPTIONS, 0));
            PlayHavenView.DismissType dismiss = (PlayHavenView.DismissType) data.getSerializableExtra(PlayHavenView.BUNDLE_DISMISS_TYPE);
            Log.d(TAG, "Ad was closed: " + dismiss);
            Bundle adData = data.getBundleExtra(PlayHavenView.BUNDLE_DATA);
            if(adData != null)
            {
                switch(dismiss)
                {
                    case Reward:
                        for(Reward reward : adData.<Reward>getParcelableArrayList(PlayHavenView.BUNDLE_DATA_REWARD))
                            Log.d(TAG, "Reward:  " +reward);
                        break;
                    case Purchase:
                        for(Purchase purchase: adData.<Purchase>getParcelableArrayList(PlayHavenView.BUNDLE_DATA_PURCHASE))
                            Log.d(TAG, "Purchase:  " +purchase);
                        break;
                    case OptIn:
                        for(DataCollectionField field : adData.<DataCollectionField>getParcelableArrayList(PlayHavenView.BUNDLE_DATA_OPTIN))
                            Log.d(TAG, "Field:  " +field);

                        for(Reward reward : adData.<Reward>getParcelableArrayList(PlayHavenView.BUNDLE_DATA_REWARD))
                            Log.d(TAG, "Reward:  " +reward);
                        break;
                    default:
                        for(String key : adData.keySet())
                            Log.d(TAG, "Ad data @ " + key);
                        break;
                }
            }

            Placement pl = data.getParcelableExtra(PlayHavenView.BUNDLE_PLACEMENT);
            if(pl != null)
                updateOutput(pl.getModel());

            // Clear out the old placement (don't re-use)
            placement = null;
        }
    }

    private void updateOutput(final String msg)
    {
        handler.post(new Runnable() {
            @Override
            public void run() {
                ((TextView) findViewById(R.id.output)).setText(msg);
            }
        });
    }

    private void updateOutput(Exception e)
    {
        updateOutput(e.getMessage());
//        final StringWriter sw = new StringWriter();
//        e.printStackTrace(new PrintWriter(sw));
//        updateOutput(sw.toString());
    }

    private void updateOutput(ClientApiResponseModel model)
    {
        try{
            updateOutput((model == null ? "" : (new DataboundMapper()).writeValueAsString(model)));
        }catch(Exception e){
            Log.w(PlayHaven.TAG, e.getMessage(), e);
        }
    }

    @Override
    public void onItemSelected(AdapterView<?> parent, android.view.View view, int position, long id) {
        if(parent == reqSpinner)
        {
            switch(getRequestTypeForTitle(parent.getItemAtPosition(position).toString()))
            {
                case Open:
                    findViewById(R.id.placementTag).setEnabled(false);
                    findViewById(R.id.overlay).setEnabled(false);
                    findViewById(R.id.animation).setEnabled(false);
                    findViewById(R.id.viewtype_spinner).setEnabled(false);
                    break;
                case Preload:
                    findViewById(R.id.placementTag).setEnabled(true);
                    findViewById(R.id.overlay).setEnabled(false);
                    findViewById(R.id.animation).setEnabled(false);
                    findViewById(R.id.viewtype_spinner).setEnabled(false);
                    break;
                case Content:
                    findViewById(R.id.placementTag).setEnabled(true);
                    findViewById(R.id.overlay).setEnabled(true);
                    findViewById(R.id.animation).setEnabled(true);
                    findViewById(R.id.viewtype_spinner).setEnabled(true);
                    break;
                case Metadata:
                    findViewById(R.id.placementTag).setEnabled(true);
                    findViewById(R.id.overlay).setEnabled(false);
                    findViewById(R.id.animation).setEnabled(false);
                    findViewById(R.id.viewtype_spinner).setEnabled(false);
                    break;
            }
            findViewById(R.id.go).setEnabled(true);
        }
    }

    @Override
    public void onNothingSelected(AdapterView<?> parent) {
        findViewById(R.id.go).setEnabled(false);
        findViewById(R.id.placementTag).setEnabled(false);
        findViewById(R.id.overlay).setEnabled(false);
        findViewById(R.id.animation).setEnabled(false);
        findViewById(R.id.viewtype_spinner).setEnabled(false);
    }


    @Override
    public void handleResponse(ClientApiResponseModel model) {
        updateOutput(model);
    }

    @Override
    public void handleResponse(PlayHavenException e) {
        updateOutput(e);
    }

    @Override
    public void viewFailed(PlayHavenView view, PlayHavenException exception) {
        updateOutput(exception);
    }

    @Override
    public void viewDismissed(PlayHavenView view, PlayHavenView.DismissType dismissType, Bundle data) {
        updateOutput("PlayHavenView#" + view.getPlacementTag() + " was dismissed: " + dismissType);
        if(data != null)
        {
            for(String key : data.keySet())
                Log.d(TAG, "Ad data @ " + key);
        }
    }

    @Override
    public void contentDismissed(Placement placement, PlayHavenView.DismissType dismissType, Bundle data)
    {
        updateOutput("contentDismissed(Placement, " + dismissType.toString() + ")");
    }

    @Override
    public void contentLoaded(Placement placement) {
        ClientApiResponseModel model = placement.getModel();
        if(model == null)
        {
            Log.d(TAG, "Content Loaded: null (" + (this.placement.getModel()==null) + ")");
            return;
        }
        updateOutput(model);
        handler.post(new Runnable() {
            @Override
            public void run() {
                findViewById(R.id.viewtype_spinner).setEnabled(true);
            }
        });
    }

    @Override
    public void contentFailed(Placement placement, PlayHavenException e) {
        updateOutput(e);
    }

    /**
     * In addition to the default receiver which will handle registration, 
     * this will update the Diagnosticapp's UI. 
     */
    private class GCMReceiver extends BroadcastReceiver {

		@Override
		public void onReceive(Context context, Intent intent) {
			PlayHaven.v("Received registration request in launcher.");
			String action = intent.getAction();
			String output = "Received GCM broadcast. ";
	        if (com.playhaven.android.push.GCMBroadcastReceiver.C2DM_REGISTRATION.equals(action)) {
	            output += " Received registration_id: " + intent.getStringExtra("registration_id");
	        } else if (com.playhaven.android.push.GCMBroadcastReceiver.C2DM_RECEIVE.equals(action)) {
	        	output += " Push notification received."; 
	        }
			updateOutput(output);
		}
    }
}
